/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.116
 * Generated at: 2026-04-10 11:22:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Error404_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>404 - Page Not Found</title>\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            background-color: #f4f4f4;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            height: 100vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-container {\n");
      out.write("            text-align: center;\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            padding: 50px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 0 20px rgba(0,0,0,0.1);\n");
      out.write("            width: 500px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-code {\n");
      out.write("            font-size: 100px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: #e74c3c;\n");
      out.write("            line-height: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-title {\n");
      out.write("            font-size: 28px;\n");
      out.write("            color: #333333;\n");
      out.write("            margin: 10px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-message {\n");
      out.write("            font-size: 16px;\n");
      out.write("            color: #777777;\n");
      out.write("            margin: 15px 0 30px 0;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-home {\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 12px 30px;\n");
      out.write("            background-color: #3498db;\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            font-size: 16px;\n");
      out.write("            margin: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-back {\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 12px 30px;\n");
      out.write("            background-color: #95a5a6;\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            font-size: 16px;\n");
      out.write("            margin: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-home:hover { background-color: #2980b9; }\n");
      out.write("        .btn-back:hover { background-color: #7f8c8d; }\n");
      out.write("\n");
      out.write("        .error-icon {\n");
      out.write("            font-size: 60px;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .divider {\n");
      out.write("            border: none;\n");
      out.write("            border-top: 1px solid #eeeeee;\n");
      out.write("            margin: 20px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-details {\n");
      out.write("            font-size: 13px;\n");
      out.write("            color: #aaaaaa;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"error-container\">\n");
      out.write("\n");
      out.write("        <div class=\"error-icon\">&#128269;</div>\n");
      out.write("\n");
      out.write("        <div class=\"error-code\">404</div>\n");
      out.write("\n");
      out.write("        <div class=\"error-title\">Page Not Found</div>\n");
      out.write("\n");
      out.write("        <hr class=\"divider\"/>\n");
      out.write("\n");
      out.write("        <div class=\"error-message\">\n");
      out.write("            Oops! The page you are looking for does not exist.<br>\n");
      out.write("            It may have been moved or deleted.\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <a href=\"index.jsp\"    class=\"btn-home\">Go to Home</a>\n");
      out.write("        <a href=\"javascript:history.back()\" class=\"btn-back\">Go Back</a>\n");
      out.write("\n");
      out.write("        <div class=\"error-details\">\n");
      out.write("            Requested URL: ");
      out.print( request.getAttribute("javax.servlet.error.request_uri") );
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>s");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
