/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.116
 * Generated at: 2026-04-10 11:17:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import java.util.List;
import com.rays.bean.User1Bean;

public final class UserListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1775819214000L));
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1775048493000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.rays.bean.User1Bean");
    _jspx_imports_classes.add("java.util.Iterator");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	");

	List<User1Bean> list = (List) request.getAttribute("list");
	List<User1Bean> nextList = (List) request.getAttribute("nextList");
	int pageNo = (int) request.getAttribute("pageNo");
	Iterator<User1Bean> it = list.iterator();

	String successMsg = (String) request.getAttribute("successMsg");
	String errorMsg = (String) request.getAttribute("errorMsg");
	
      out.write('\n');
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	");

	User1Bean user1Bean = (User1Bean) session.getAttribute("user");
	
      out.write('\n');
      out.write('\n');
      out.write('	');

	if (user1Bean != null) {
	
      out.write("\n");
      out.write("	<h1>");
      out.print("Hii, " + user1Bean.getFirstName());
      out.write("</h1>\n");
      out.write("	<a href=\"UserCtl.do\">Add User</a> |\n");
      out.write("	<a href=\"UserListCtl.do\">User List</a> |\n");
      out.write("	<a href=\"LoginCtl?operation=logout\">Logout</a> |\n");
      out.write("	<a href=\"\">Marksheet</a> |\n");
      out.write("	");

	} else {
	
      out.write("\n");
      out.write("\n");
      out.write("	<h3>Hii, Guest</h3>\n");
      out.write("	<a href=\"LoginCtl\">Login</a> |\n");
      out.write("	<a href=\"UserRegistrationCtl\">Sign Up</a> |\n");
      out.write("	<a href=\"\">Marksheet</a> |\n");
      out.write("	");

	}
	
      out.write("\n");
      out.write("	<a href=\"WelcomeCtl\">Welcome</a>\n");
      out.write("	<hr>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<h1 align=\"center\" style=\"color: darkblue\">\n");
      out.write("		<u>User List</u>\n");
      out.write("	</h1>\n");
      out.write("\n");
      out.write("	<form action=\"UserListCtl.do\" method=\"post\">\n");
      out.write("		<div  align=\"center\">\n");
      out.write("			<h2 style=\"color: green\">");
      out.print(successMsg != null ? successMsg : "");
      out.write("</h2>\n");
      out.write("			<h2 style=\"color: red\">");
      out.print(errorMsg != null ? errorMsg : "");
      out.write("</h2>\n");
      out.write("\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		");

		if (list.size() == 0) {
		
      out.write("\n");
      out.write("		<div align=\"center\">\n");
      out.write("			<h1 style=\"color: red\">Record Not found</h1>\n");
      out.write("			");

			} else {
			
      out.write("\n");
      out.write("			<input type=\"hidden\" name=\"pageNo\" value=\"");
      out.print(pageNo);
      out.write("\">\n");
      out.write("\n");
      out.write("			<div align=\"center\">\n");
      out.write("				<table>\n");
      out.write("					<tr>\n");
      out.write("						<th>First Name</th>\n");
      out.write("						<td><input type=\"text\" name=\"firstName\"\n");
      out.write("							value=\"");
      out.print(request.getParameter("firstName") != null ? request.getParameter("firstName") : "");
      out.write("\"\n");
      out.write("							placeholder=\"search by firstName\"></td>\n");
      out.write("						<th>Last Name</th>\n");
      out.write("						<td><input type=\"text\" name=\"lastName\"\n");
      out.write("							value=\"");
      out.print(request.getParameter("lastName") != null ? request.getParameter("lastName") : "");
      out.write("\"\n");
      out.write("							placeholder=\"search by last name\"></td>\n");
      out.write("						<th>Login</th>\n");
      out.write("						<td><input type=\"text\" name=\"login\"\n");
      out.write("							value=\"");
      out.print(request.getParameter("login") != null ? request.getParameter("login") : "");
      out.write("\"\n");
      out.write("							placeholder=\"search by login\"></td>\n");
      out.write("						<td><input type=\"submit\" name=\"operation\" value=\"search\"></td>\n");
      out.write("					</tr>\n");
      out.write("				</table>\n");
      out.write("				<table width=\"100%\" border=\"1px\">\n");
      out.write("					<tr style=\"background-color: skyblue\">\n");
      out.write("						<th>Select</th>\n");
      out.write("						<th>Id</th>\n");
      out.write("						<th>First Name</th>\n");
      out.write("						<th>Last Name</th>\n");
      out.write("						<th>Login</th>\n");
      out.write("						<th>Password</th>\n");
      out.write("						<th>Dob</th>\n");
      out.write("						<th>Edit</th>\n");
      out.write("					</tr>\n");
      out.write("\n");
      out.write("					");

					while (it.hasNext()) {
						User1Bean bean = it.next();
					
      out.write("\n");
      out.write("\n");
      out.write("					<tr align=\"center\" style=\"background-color: #D3D3D3;\">\n");
      out.write("						<td><input type=\"checkbox\" name=\"ids\" value=");
      out.print(bean.getId());
      out.write("></td>\n");
      out.write("						<td>");
      out.print(bean.getId());
      out.write("</td>\n");
      out.write("						<td>");
      out.print(bean.getFirstName());
      out.write("</td>\n");
      out.write("						<td>");
      out.print(bean.getLastName());
      out.write("</td>\n");
      out.write("						<td>");
      out.print(bean.getLogin());
      out.write("</td>\n");
      out.write("						<td>");
      out.print(bean.getPassword());
      out.write("</td>\n");
      out.write("						<td>");
      out.print(bean.getDob());
      out.write("</td>\n");
      out.write("				<td><a href=\"UserCtl.do?id=");
      out.print(bean.getId());
      out.write("\">Edit</a></td>\n");
      out.write("					</tr>\n");
      out.write("					");

					}
					
      out.write("\n");
      out.write("				</table>\n");
      out.write("			</div>\n");
      out.write("			<div>\n");
      out.write("				<table width=\"100%\">\n");
      out.write("					<tr>\n");
      out.write("						<td><input type=\"submit\" name=\"operation\"\n");
      out.write("							");
      out.print(pageNo == 1 ? "disabled" : "");
      out.write(" value=\"previous\"></td>\n");
      out.write("						<td><input type=\"submit\" name=\"operation\" value=\"delete\"></td>\n");
      out.write("						<td align=\"right\"><input type=\"submit\" name=\"operation\"\n");
      out.write("							");
      out.print( nextList.size() == 0 ? "disabled" : "");
      out.write(" value=\"next\"></td>\n");
      out.write("					</tr>\n");
      out.write("				</table>\n");
      out.write("			</div>\n");
      out.write("			");

			}
			
      out.write("\n");
      out.write("		\n");
      out.write("	</form>\n");
      out.write("\n");
      out.write("	");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#footer {\n");
      out.write("	position: fixed;\n");
      out.write("	left: 0;\n");
      out.write("	width: 100%;\n");
      out.write("	bottom: 0;\n");
      out.write("	background-color: white;\n");
      out.write("	color: black;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<div id=\"footer\">\n");
      out.write("		<CENTER>\n");
      out.write("			<hr>\n");
      out.write("			<H3>All rights reserved by Rays Technologies, SunilOS Infotech\n");
      out.write("				Pvt Ltd Copyright &copy; 2026</H3>\n");
      out.write("		</CENTER>\n");
      out.write("	</div>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
